package rdata

import (
	"os"
	"testing"
)

// Golden files generated by R 4.6.0 (saveRDS/save). df is 8x5, mat is 10x20,
// multi.RData holds df (8x5), m (10x20) and x (a length-50 vector, not a grid).
func TestGridsRealFixtures(t *testing.T) {
	cases := []struct {
		file string
		want []Grid
	}{
		{"testdata/df.rds", []Grid{{Rows: 8, Cols: 5}}},
		{"testdata/mat.rds", []Grid{{Rows: 10, Cols: 20}}},
		{"testdata/multi.RData", []Grid{{Rows: 8, Cols: 5}, {Rows: 10, Cols: 20}}},
	}
	for _, c := range cases {
		raw, err := os.ReadFile(c.file)
		if err != nil {
			t.Fatalf("%s: %v", c.file, err)
		}
		got, err := Grids(raw, 0)
		if err != nil {
			t.Fatalf("%s: Grids error: %v", c.file, err)
		}
		if !sameGrids(got, c.want) {
			t.Errorf("%s: got %v, want %v", c.file, got, c.want)
		}
	}
}

func sameGrids(a, b []Grid) bool {
	if len(a) != len(b) {
		return false
	}
	// order-insensitive compare
	used := make([]bool, len(b))
	for _, x := range a {
		found := false
		for i, y := range b {
			if !used[i] && x == y {
				used[i] = true
				found = true
				break
			}
		}
		if !found {
			return false
		}
	}
	return true
}
